name: 'Setup for pipeline'
description: 'Common setup for my Android pipelines'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
